20230930/bookproject -1_4章終了/book/urls.py
from django.urls import path
from . import views

app_name = "book"

urlpatterns = [
    path("book/",views.ListBookView.as_view(),name="list-book"),
    path("book/<int:pk>/detail/",views.DetailBookView.as_view(),name="detail-book"),
    path("book/create/",views.CreateBookView.as_view(),name="create-book"),
    path("book/<int:pk>/delete",views.DeleteBookView.as_view(),name="delete-book"),
    path("book/<int:pk>/update",views.UpdateBookView.as_view(),name="update-book")
]

20230930/bookproject -1_4章終了/bookproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("book.urls")),
]

20230930/bookproject -1_4章終了/book/models.py
from django.db import models

# Create your models here.
CATEGORY = (("business","ビジネス"),("life","生活"),("other","その他"))


class Book(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    category = models.CharField(max_length=100,choices=CATEGORY)

    def __str__(self):
        return self.title+"："+self.text

20230930/bookproject -1_4章終了/book/views.py
from django.shortcuts import render
from .models import Book
from django.views.generic import ListView,DetailView,CreateView,DeleteView,UpdateView
from django.urls import reverse_lazy
# Create your views here.

class ListBookView(ListView):
    template_name = "book/book_list.html"
    model = Book

class DetailBookView(DetailView):
    template_name = "book/book_detail.html"
    model = Book

class CreateBookView(CreateView):
    template_name = "book/book_create.html"
    model = Book
    fields = ("title","text","category")
    success_url = reverse_lazy("book:list-book")

class DeleteBookView(DeleteView):
    template_name = "book/book_delete.html"
    model = Book
    success_url = reverse_lazy("book:list-book")

class UpdateBookView(UpdateView):
    template_name = "book/book_update.html"
    model = Book
    fields = ("title","text","category")
    success_url = reverse_lazy("book:list-book")

20230930/bookproject -1_4章終了/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" 
    rel="stylesheet" 
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" 
    crossorigin="anonymous">
    <title>{%block title%}{%endblock%}|本棚アプリ</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-success sticky-top">
        <div class="navbar-nav d-flex flex-row">
            <a class="nav-link mx-3" href="{%url 'book:list-book'%}">書籍一覧</a>
            <a class="nav-link mx-3" href="{%url 'book:create-book'%}">書籍登録</a>
        </div>
    </nav>
    <div class="p-4">
        <h1>{%block h1%}{%endblock%}</h1>

        {%block content%}{%endblock%}
    </div>
</body>
</html>