20230930/bookproject -8_自分の投稿だけ操作可能完了/book/urls.py
from django.urls import path
from . import views

app_name = "book"

urlpatterns = [
    path("",views.index_view,name="index"),
    path("book/",views.ListBookView.as_view(),name="list-book"),
    path("book/<int:pk>/detail/",views.DetailBookView.as_view(),name="detail-book"),
    path("book/create/",views.CreateBookView.as_view(),name="create-book"),
    path("book/<int:pk>/delete/",views.DeleteBookView.as_view(),name="delete-book"),
    path("book/<int:pk>/update/",views.UpdateBookView.as_view(),name="update-book"),
    path("book/<int:book_id>/review/",views.CreateReviewView.as_view(),name="review"),
]

20230930/bookproject -8_自分の投稿だけ操作可能完了/book/models.py
from django.db import models
from . import consts

# Create your models here.
CATEGORY = (("business","ビジネス"),("life","生活"),("other","その他"))
RATE_CHOICES = [(x,str(x)) for x in range(0,consts.MAX_RATE+1)]


class Book(models.Model):
    title = models.CharField(max_length=100)
    text = models.TextField()
    gazou = models.ImageField(null=True,blank=True)
    category = models.CharField(max_length=100,choices=CATEGORY)
    user = models.ForeignKey("auth.User",on_delete=models.CASCADE)

    def __str__(self):
        return self.title+"："+self.text
    
class Review(models.Model):
    book = models.ForeignKey(Book,on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    text = models.TextField()
    rate = models.IntegerField(choices=RATE_CHOICES)
    user = models.ForeignKey("auth.User",on_delete=models.CASCADE)

    def __str__(self):
        return self.title+"："+self.text

20230930/bookproject -8_自分の投稿だけ操作可能完了/book/views.py
from typing import Any
from django.db import models
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from .models import Book,Review
from django.views.generic import ListView,DetailView,CreateView,DeleteView,UpdateView
from django.urls import reverse_lazy,reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
# Create your views here.

class ListBookView(LoginRequiredMixin,ListView):
    template_name = "book/book_list.html"
    model = Book

class DetailBookView(LoginRequiredMixin,DetailView):
    template_name = "book/book_detail.html"
    model = Book

class CreateBookView(LoginRequiredMixin,CreateView):
    template_name = "book/book_create.html"
    model = Book
    fields = ("title","text","category","gazou")
    success_url = reverse_lazy("book:list-book")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class DeleteBookView(LoginRequiredMixin,DeleteView):
    template_name = "book/book_delete.html"
    model = Book

    def get_object(self, queryset=None):
        obj =  super().get_object(queryset)
    
        if obj.user != self.request.user:
            raise PermissionDenied
        
        return obj
    
    def get_success_url(self):
        return reverse("book:list-book",kwargs={"pk":self.object.id})

class UpdateBookView(LoginRequiredMixin,UpdateView):
    template_name = "book/book_update.html"
    model = Book
    fields = ("title","text","category","gazou")
    
    def get_object(self, queryset=None):
        obj =  super().get_object(queryset)
    
        if obj.user != self.request.user:
            raise PermissionDenied
        
        return obj
    
    def get_success_url(self):
        return reverse("book:detail-book",kwargs={"pk":self.object.id})

def index_view(request):
    object_list = Book.objects.order_by("category")
    return render(request,"book/index.html",{"object_list":object_list})

class CreateReviewView(CreateView):
    template_name = "book/review_form.html"
    model = Review
    fields = ("book","title","text","rate")

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context["book"] = Book.objects.get(pk=self.kwargs["book_id"])
        return context
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse("book:detail-book",kwargs={"pk":self.object.book.id})

20230930/bookproject -8_自分の投稿だけ操作可能完了/book/templates/book/book_create.html
{%extends "base.html"%}

{%block title%}書籍登録{%endblock%}

{%block h1%}書籍登録{%endblock%}

{%block content%}
    <form method="post" action="" enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="作成する">
    </form>
{%endblock%}

20230930/bookproject -8_自分の投稿だけ操作可能完了/book/templates/book/book_delete.html
{%extends "base.html"%}

{%block title%}書籍削除{%endblock%}

{%block h1%}書籍削除{%endblock%}

{%block content%}
    <form method="post" action="">
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="削除する">
    </form>
{%endblock%}

20230930/bookproject -8_自分の投稿だけ操作可能完了/book/templates/book/book_detail.html
{%extends "base.html"%}

{%block title%}{{object.title}}{%endblock%}

{%block h1%}書籍詳細{%endblock%}

{%block content%}
    <div class="p-4 bg-light border border-success rounded">
        <h2 class="text-success">{{object.title}}</h2>
        <p>{{object.text}}</p>
        <a href="{%url 'book:list-book'%}" class="btn btn-primary">一覧へ</a>
        <a href="{%url 'book:review' object.pk%}" class="btn btn-primary">レビューする</a>
        <a href="{%url 'book:update-book' object.pk%}" class="btn btn-primary">編集する</a>
        <a href="{%url 'book:delete-book' object.pk%}" class="btn btn-primary">削除する</a>
        <h6 class="card-title">{{object.category}}</h6>
    </div>
{%endblock%}

20230930/bookproject -8_自分の投稿だけ操作可能完了/book/templates/book/book_list.html
{%extends "base.html"%}

{%block title%}書籍一覧{%endblock%}

{%block h1%}書籍一覧{%endblock%}

{%block content%}
    {%for item in object_list%}
        <div class="p-4 m-4 bg-light border border-success rounded">
            <h2 class="text-success">{{item.title}}</h2>
            <h6>カテゴリ:{{item.category}}</h6>
            <div class="mt-3">
                <a href="{%url 'book:detail-book' item.pk%}">詳細へ</a>
            </div>
        </div>
    {%endfor%}
{%endblock%}

20230930/bookproject -8_自分の投稿だけ操作可能完了/book/templates/book/book_update.html
{%extends "base.html"%}

{%block title%}書籍更新{%endblock%}

{%block h1%}書籍更新{%endblock%}

{%block content%}
    <form method="post" action="" enctype="multipart/form-data" class="p-4 m-4 bg-light border border-success rounded form-group">
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="更新する">
    </form>
{%endblock%}

20230930/bookproject -8_自分の投稿だけ操作可能完了/book/templates/book/index.html
{%extends "base.html"%}

{%block title%}top{%endblock%}

{%block h1%}書籍一覧{%endblock%}

{%block content%}
    {%for item in object_list%}
        <div class="p-4 m-4 bg-light border border-success rounded">
            <h2 class="text-success">{{item.title}}</h2>
            <img src="{{item.gazou.url}}" class="img-thumbnail"/>
            <h6>カテゴリ:{{item.category}}</h6>
            <div class="mt-3">
                <a href="{%url 'book:detail-book' item.pk%}">詳細へ</a>
            </div>
        </div>
    {%endfor%}
{%endblock%}

20230930/bookproject -8_自分の投稿だけ操作可能完了/book/templates/book/review_form.html
{%extends "base.html"%}

{%block title%}レビュー投稿{%endblock%}

{%block h1%}レビュー投稿{%endblock%}

{%block content%}
    <form method="post" class="p-4 m-4 bg-light border border-success rounded form-group" action="">
        {%csrf_token%}
        <label for="">対象書籍</label>
        <input class="form-control" type="text" value="{{book.title}}" readonly>

        <label for="">タイトル</label>
        <input class="form-control" type="text" name="title">

        <label for="">本文</label>
        <textarea class="form-control" name="text" id="" cols="" rows=""></textarea>

        <label for="">星の数</label>
        <select name="rate" id="" class="form-control">
            <option value="0">ー</option>
            <option value="1">★☆☆☆☆</option>
            <option value="2">★★☆☆☆</option>
            <option value="3">★★★☆☆</option>
            <option value="4">★★★★☆</option>
            <option value="5">★★★★★</option>
        </select>
        <input type="hidden" name="book" value="{{book.id}}">
        <button type="submit" class="btn btn-success mt-4">投稿する</button>
    </form>
{%endblock%}